version: '3.1'
services:
  mysql:
    image: mysql:5.5
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3335:3306

  shopping-s3:
    image: minio/minio:RELEASE.2021-02-11T08-23-43Z
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: shopping-minio
      MINIO_ROOT_PASSWORD: shopping-minio
    command: server /data

#  mongodb:
#    image: mongo:latest
#     container_name: mongodb
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: <admin-user>
#       MONGO_INITDB_ROOT_PASSWORD: <admin-password>
#       MONGO_INITDB_DATABASE: <database to create>
#     ports:
#       - 27017:27017
#     volumes:
#       - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  shopping-ms_mysql_db_data:
