server:
  port: ${SERVER_PORT:8088}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: user-service
                fallbackUri: forward:/fb/users

        - id: movie-service
          uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/api/movies/**
          filters:
            - RewritePath=/api/movies/(?<segment>.*), /$\{segment}
            - name: Hystrix
              args:
                name: movie-service
                fallbackUri: forward:/fb/movies

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8500}/eureka/
    register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

ribbon:
  ReadTimeout: 60000

authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer

api:
  registration:
    url:
      path : /users-ws/users
  login:
    url:
      path : /users-ws/users/login
  zuul:
    actuactor:
      url:
        path: /actuator/*

management.endpoints.web.exposure.include=beans,health,routes,httptrace
